### ISSUE TITLE
각종 업데이트

### ISSUE THREAD

**Issue by hemoptysisheart** [hemoptysisheart/android-template#1]
구버전, 빠진 것들이 좀 된다.

## TODO

- [x] 리드미
  - [x]  패키지 변경.
  - [x]  IDE 실행 설정 `clean app`의 모듈을 다시 지정하기.
  - [x] 템플릿 이름 수정.
- [x]  내비게이션 그래프 샘플을 스플래시, 메인 페이지로 추가하기.
- [x]  매니페스트에서 `tools:targetApi` 삭제.
- [x] 라이브러리, SDK 업데이트.
